name: build-framework
on:
  push:
    branches:
      - 'setup'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: project.yml
          version: '2.33.0'
      - run: fastlane build_framework
  unit_test:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: project.yml
          version: '2.33.0'
      - run: fastlane unit_test
  ui_tests:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: project.yml
          version: '2.33.0'
      - run: fastlane ui_tests
