name: build-framework
on:
  push:
    branches:
      - 'setup'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: project.yaml
          quiet: false
          version: '2.33.0'
      - run: fastlane build_framework
